'use strict';
const $=id=>document.getElementById(id);
let state=null, csrf='', online=false, pending=false, formLoaded=false, scheduleLoaded=false, toastTimer;
const labels={disabled:'Disabled',ended:'Ended',waiting:'Waiting',new:'Waiting',preparing:'Preparing',prepared:'Prepared',starting:'Starting',live:'Start confirmed',done:'Start confirmed',missed:'Skipped',needs_review:'Needs review',patrol_sending:'Patrol starting'};
const fields=[['obs_exe','OBS executable'],['obs_port','OBS WebSocket port'],['obs_password','OBS WebSocket password','password'],['obs_profile','OBS profile'],['obs_collection','Scene collection'],['obs_scene','Program scene'],['fb_target','Facebook output target'],['google_client_file','Google Desktop OAuth JSON path'],['facebook_page_token','Facebook Page access token','password'],['graph_version','Meta Graph API version'],['camera_url','Camera base address'],['camera_user','Camera username'],['camera_password','Camera password','password']];
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6500);}
async function api(path,data){const options={cache:'no-store',signal:AbortSignal.timeout(15000)};if(data!==undefined){options.method='POST';options.headers={'Content-Type':'application/json','X-CSRF-Token':csrf};options.body=JSON.stringify(data);}const res=await fetch(path,options);const out=await res.json();if(!res.ok){if(res.status===401&&path!='/api/login')showLogin();throw new Error(out.error||'Request failed.');}return out;}
function showLogin(){$('app').hidden=true;$('login').hidden=false;online=false;state=null;csrf='';formLoaded=false;scheduleLoaded=false;}
async function pair(code){await api('/api/login',{code});$('pair-code').value='';$('pair-error').textContent='';await refresh();}
$('pair-form').addEventListener('submit',async event=>{event.preventDefault();const b=event.submitter;b.disabled=true;try{await pair($('pair-code').value.trim());}catch(e){$('pair-error').textContent=e.message;}finally{b.disabled=false;}});
function navigate(view){if(!['overview','schedule','connections','activity','mobile','updates'].includes(view))view='overview';document.querySelectorAll('.view').forEach(n=>n.hidden=n.id!=='view-'+view);document.querySelectorAll('[data-view]').forEach(n=>{n.classList.toggle('active',n.dataset.view===view);if(n.dataset.view===view)n.setAttribute('aria-current','page');else n.removeAttribute('aria-current');});$('page-title').textContent={overview:'Live overview',schedule:'Daily schedule',connections:'Connections',activity:'Activity',mobile:'Mobile access',updates:'App updates'}[view];history.replaceState(null,'','#'+view);}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));
function makeSlots(target,full){const parent=$(target);parent.replaceChildren();for(const s of state.slots){const row=el('div','slot'+(s.name===state.next.name?' next':''));const time=el('div','slot-time',s.at);time.append(el('small','','IST'));const name=el('div');name.append(el('div','slot-name',s.name),el('div','slot-dest',full&&s.last_error?s.last_error:(s.end_at?'End '+s.end_at+(s.end_next_day?' +1 day':'')+' · YouTube + Facebook':'Manual end · YouTube + Facebook')));const status=el('span','slot-state'+(s.phase==='needs_review'||s.end_state==='needs_review'?' attention':['live','done'].includes(s.phase)?' confirmed':''),s.end_state==='needs_review'?'End needs review':labels[s.phase]||s.phase);row.append(time,name,status);parent.append(row);}}
function render(){
 $('app-version').textContent=state.app_version||'—';$('open-updates').hidden=!state.local;$('updates-help').textContent=state.local?'Pause automation and finish any active live or recording before installing.':'Manage updates from the Windows PC. Your phone will reconnect after the app restarts and may need pairing again.';
 $('login').hidden=true;$('app').hidden=false;$('offline').hidden=true;$('today').textContent=state.date;$('status-message').textContent=state.message;$('status-message').classList.toggle('error',state.error);
 $('link-state').textContent='● PC connected';$('link-state').className='badge good';$('next-name').textContent=state.next.name;$('next-time').textContent=state.next.at;$('arm-badge').textContent=state.armed?'Automation enabled':state.arm_requested&&state.busy?'Waiting for connections':'Automation paused';
 const sameDay=state.next.due.slice(0,10)===state.now.slice(0,10);$('next-day').textContent=sameDay?'Today':'Tomorrow';
 const cards=$('connection-cards');cards.replaceChildren();for(const [key,title,detail,icon] of [['obs','OBS Studio','Program scene on the PC','◉'],['youtube','YouTube','ISKCON Kolkata Official','▶'],['facebook','Facebook','Iskcon Kolkata [Official]','f'],['camera','PTZ camera','Channel 1 · Patrol 8','◈']]){const card=el('article','connection-card'),top=el('div','service-top');top.append(el('span','service-icon '+key,icon),el('span','service-state '+state.connections[key],state.connections[key]==='verified'?'● Verified':'○ Not checked'));card.append(top,el('div','service-name',title),el('div','service-detail',detail));cards.append(card);}
 $('checked-at').textContent=state.checked?'Last full check: '+new Date(state.checked).toLocaleTimeString('en-GB',{timeZone:'Asia/Kolkata'})+' IST · This is a connection check, not current live status.':'Connection status reflects checks in this app session.';
 makeSlots('schedule-preview',false);makeSlots('schedule-full',true);if(!scheduleLoaded)buildSchedule();$('program-count').textContent=state.schedule.filter(s=>s.enabled).length+' enabled';$('export-diagnostics').hidden=!state.local;
 const logs=$('log-list');const atBottom=logs.scrollHeight-logs.scrollTop-logs.clientHeight<60;logs.replaceChildren();for(const item of state.logs){const row=el('div','log-entry'+(/failed|attention|review|error/i.test(item.message)?' log-error':''));row.append(el('span','log-time',item.time),el('span','',item.message));logs.append(row);}if(atBottom)logs.scrollTop=logs.scrollHeight;
 $('remote-settings').hidden=state.local;$('settings-form').hidden=!state.local;
 if(state.local&&!formLoaded){const grid=$('settings-fields');grid.replaceChildren();for(const [key,label,type] of fields){const wrap=el('div','field'),l=el('label','',label),input=el('input');input.id='field-'+key;input.name=key;input.type=type||'text';input.autocomplete='off';input.value=type==='password'?'':state.settings[key]||'';if(type==='password')input.placeholder='Saved value retained when blank';l.htmlFor=input.id;wrap.append(l,input);grid.append(wrap);}formLoaded=true;}
 const addresses=$('phone-addresses');addresses.replaceChildren();if(!state.local)addresses.textContent='This phone is paired. Controls are available in Overview.';else if(!state.mobile_enabled)addresses.textContent='Mobile access is currently off. Enable it from the Windows launcher.';else{addresses.append(el('b','','Phone address'));state.mobile_urls.forEach(url=>{const p=el('p'),a=el('a','',url);a.href=url;p.append(a);addresses.append(p);});if(!state.mobile_urls.length)addresses.append(el('p','','Check the Windows launcher for your network address.'));}
 updateButtons();updateClock();
}
function updateButtons(){const busy=!online||pending;for(const id of ['arm','check','check-settings','retry','save-settings','connect-youtube','save-schedule','reload-schedule'])$(id).disabled=busy||!!state?.busy;$('pause').disabled=busy||!(state?.armed||state?.busy);document.querySelectorAll('#schedule-form input,#schedule-form select,#schedule-form button').forEach(i=>i.disabled=busy||!!state?.busy);document.querySelectorAll('#settings-form input').forEach(i=>i.disabled=busy||!!state?.busy);}
function updateClock(){if(!state)return;const now=new Date(Date.parse(state.now)+(Date.now()-state.received));$('clock').replaceChildren(document.createTextNode(now.toLocaleTimeString('en-GB',{timeZone:'Asia/Kolkata'})+' '),el('small','','IST'));const diff=Math.max(0,Date.parse(state.next.due)-now.getTime()),mins=Math.floor(diff/60000),h=Math.floor(mins/60),m=mins%60;$('countdown').textContent=(state.armed?'Starts in ':'Next program in ')+(h?h+'h ':'')+m+'m'+(state.armed?'':' · enable automation to run this schedule');}
async function refresh(){try{const out=await api('/api/state');state={...out,received:Date.now()};csrf=out.csrf;online=true;render();}catch(e){if(state){online=false;$('offline').hidden=false;$('link-state').textContent='○ PC disconnected';$('link-state').className='badge';updateButtons();}else if(!$('login').hidden){}else showLogin();}}
function confirmAction(title,message){return new Promise(resolve=>{const d=$('confirm-dialog');$('confirm-title').textContent=title;$('confirm-text').textContent=message;const finish=value=>{d.oncancel=null;$('confirm-ok').onclick=null;$('confirm-cancel').onclick=null;d.close();resolve(value);};$('confirm-ok').onclick=()=>finish(true);$('confirm-cancel').onclick=()=>finish(false);d.oncancel=e=>{e.preventDefault();finish(false);};d.showModal();$('confirm-cancel').focus();});}
async function action(name,extra={}){if(!online||pending)return;pending=true;updateButtons();try{await api('/api/action',{action:name,...extra});await refresh();}catch(e){toast(e.message);}finally{pending=false;updateButtons();}}
$('arm').onclick=async()=>{if(await confirmAction('Enable your saved automation plan?','The PC will create broadcasts and start live at your saved times. Any end times will end this app’s YouTube/Facebook broadcasts and associated OBS outputs. Camera actions will run as configured. Check the Schedule tab and OBS scene before confirming.'))action('arm',{confirmed:true});};
$('pause').onclick=()=>action('pause');$('check').onclick=()=>action('check');$('check-settings').onclick=()=>action('check');$('connect-youtube').onclick=()=>action('youtube');
$('retry').onclick=async()=>{if(await confirmAction('Have you checked both platforms?','Only continue after inspecting OBS, YouTube and Facebook for a partial live or duplicate event. This resets the selected program for its scheduled window. It does not immediately start a live.'))action('retry',{slot:$('retry-slot').value,confirmed:true});};
$('settings-form').onsubmit=async e=>{e.preventDefault();if(pending||!online)return;pending=true;updateButtons();try{const data={};for(const [key] of fields)data[key]=$('field-'+key).value;await api('/api/settings',data);fields.filter(f=>f[2]==='password').forEach(([key])=>$('field-'+key).value='');toast('Settings saved.');await refresh();}catch(err){toast(err.message);}finally{pending=false;updateButtons();}};
$('mobile-logout').onclick=$('logout').onclick=async()=>{try{await api('/api/logout',{});showLogin();}catch(e){toast(e.message);}};
$('copy-log').onclick=async()=>{try{const text=state.logs.map(r=>r.time+'  '+r.message).join('\n');if(navigator.clipboard)await navigator.clipboard.writeText(text);else{const t=el('textarea');t.value=text;document.body.append(t);t.select();if(!document.execCommand('copy'))throw new Error();t.remove();}toast('Activity copied.');}catch(e){toast('Select and copy the activity text manually.');}};
function inputField(parent,label,name,type,value){const wrap=el('label','editor-field'),input=el('input');wrap.append(el('span','',label));input.dataset.field=name;input.type=type;if(type==='checkbox')input.checked=!!value;else input.value=value??'';wrap.append(input);parent.append(wrap);return input;}
function selectField(parent,label,name,value,choices){const wrap=el('label','editor-field'),select=el('select');wrap.append(el('span','',label));select.dataset.field=name;for(const [v,t] of choices){const o=el('option','',t);o.value=v;select.append(o);}select.value=value;wrap.append(select);parent.append(wrap);return select;}
function addCameraRow(container,a={kind:'patrol_start',number:8,timing:'after_live',delay_seconds:120,at:'',next_day:false,only_if_live:true}){
 const row=el('div','camera-editor-row');
 const kind=selectField(row,'Camera action','kind',a.kind,[['patrol_start','Start patrol'],['patrol_stop','Stop patrol'],['preset','Go to preset']]);
 const number=inputField(row,'Number','number','number',a.number);number.min=1;number.max=a.kind==='preset'?32:8;
 kind.onchange=()=>{number.max=kind.value==='preset'?32:8;};
 const timing=selectField(row,'When','timing',a.timing,[['after_live','After BOTH go live'],['clock','At a clock time']]);
 const delay=inputField(row,'Delay (seconds)','delay_seconds','number',a.delay_seconds);delay.min=0;delay.max=43200;
 const at=inputField(row,'Clock time (IST)','at','time',a.at);const nd=inputField(row,'Next day','next_day','checkbox',a.next_day);const only=inputField(row,'Only while BOTH live','only_if_live','checkbox',a.only_if_live);
 function timingChanged(){const clock=timing.value==='clock';delay.parentElement.hidden=clock;at.parentElement.hidden=!clock;nd.parentElement.hidden=!clock;only.parentElement.hidden=!clock;}
 timing.onchange=timingChanged;timingChanged();
 const remove=el('button','text-button remove-action','Remove');remove.type='button';remove.onclick=()=>row.remove();row.append(remove);container.append(row);
}
function buildSchedule(){if(!state?.schedule)return;$('grace-minutes').value=state.grace_minutes;const editor=$('schedule-editor');editor.replaceChildren();$('retry-slot').replaceChildren();for(const s of state.schedule){const panel=el('article','panel schedule-program');panel.dataset.slot=s.id;const title=el('div','section-head');title.append(el('h3','',s.name));inputField(title,'Enabled','enabled','checkbox',s.enabled);panel.append(title);const times=el('div','schedule-times');inputField(times,'Live start (IST)','at','time',s.at);inputField(times,'Live end (optional)','end_at','time',s.end_at);inputField(times,'End on next day','end_next_day','checkbox',s.end_next_day);panel.append(times,el('h4','','Camera steps'));const actions=el('div','camera-editor');s.camera_actions.forEach(a=>addCameraRow(actions,a));panel.append(actions);const add=el('button','secondary add-action','+ Add camera step');add.type='button';add.onclick=()=>{if(actions.children.length>=8)return toast('Maximum 8 camera steps per program.');addCameraRow(actions);};panel.append(add,el('p','hint','Patrol 1–8 · ordinary position presets 1–32. Untick “Only while BOTH live” only for an intentional clock-based action, such as positioning before the stream.'));editor.append(panel);const option=el('option','',s.at+' — '+s.name);option.value=s.id;$('retry-slot').append(option);}scheduleLoaded=true;}
function readEditor(){const read=(row,key)=>{const i=row.querySelector('[data-field="'+key+'"]');return i.type==='checkbox'?i.checked:i.type==='number'?Number(i.value):i.value;};return [...document.querySelectorAll('.schedule-program')].map(panel=>({id:panel.dataset.slot,at:read(panel,'at'),end_at:read(panel,'end_at'),end_next_day:read(panel,'end_next_day'),enabled:read(panel,'enabled'),camera_actions:[...panel.querySelectorAll('.camera-editor-row')].map(row=>Object.fromEntries(['kind','number','timing','delay_seconds','at','next_day','only_if_live'].map(k=>[k,read(row,k)])))}));}
$('reload-schedule').onclick=async()=>{if(await confirmAction('Discard unsaved edits?','The editor will reload your currently saved schedule.')){scheduleLoaded=false;buildSchedule();updateButtons();}};
$('schedule-form').onsubmit=async event=>{event.preventDefault();if(!online||pending)return;const schedule=readEditor();const summary=schedule.filter(s=>s.enabled).map(s=>s.at+' '+state.schedule.find(x=>x.id===s.id).name+' → '+(s.end_at?'end '+s.end_at+(s.end_next_day?' next day':''):'manual end')+'; '+s.camera_actions.length+' camera step(s)').join('\n');if(!await confirmAction('Save these timings?',summary+'\n\nClock camera steps without the live-only option can move the camera even before a live starts.'))return;pending=true;updateButtons();try{await api('/api/schedule',{schedule,grace_minutes:Number($('grace-minutes').value),confirmed:true});scheduleLoaded=false;await refresh();toast('Schedule saved. Enable automation when ready.');}catch(e){toast(e.message);}finally{pending=false;updateButtons();}};
$('export-diagnostics').onclick=async()=>{try{const data=await api('/api/diagnostics');const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='ISKCON-diagnostics.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Diagnostics downloaded. Send this file to investigate the missed start.');}catch(e){toast(e.message);}};
(async()=>{const fragment=location.hash.slice(1);if(fragment.startsWith('pair=')){history.replaceState(null,'','/');try{await pair(decodeURIComponent(fragment.slice(5)));}catch(e){showLogin();$('pair-error').textContent=e.message;}}else{navigate(fragment||'overview');await refresh();}setInterval(refresh,3000);setInterval(updateClock,1000);})();

$('open-updates').onclick=async()=>{try{await api('/api/updates/open',{});toast('Update controls opened in the Windows launcher.');}catch(e){toast(e.message);}};
